In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Check columns

In [3]:
# Check columns
fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/data_for_model_annminmax/r06/loygo.csv'
pd.read_csv(fn).columns

Index(['Area', 'Aspect', 'Slope', 'Zmax', 'Zmed', 'Zmin', 'cenlat', 'cenlon',
       'rgi_id', 'year', 'mass_balance',
       'surface_solar_radiation_downwards_sum_agg',
       'surface_solar_radiation_downwards_sum_min',
       'surface_solar_radiation_downwards_sum_max', 'temperature_2m_agg',
       'temperature_2m_min', 'temperature_2m_max',
       'total_precipitation_sum_agg', 'total_precipitation_sum_min',
       'total_precipitation_sum_max'],
      dtype='object')

In [4]:
fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/annual/r06/loygo.csv'
pd.read_csv(fn).columns

Index(['rgi_id', 'year', 'GLIMSId', 'CenLon', 'CenLat', 'Slope', 'Area',
       'Aspect', 'Zmed', 'Zmin', 'Zmax', 'tas_mean', 'tas_median', 'tas_min',
       'tas_max', 'tas_std', 'rsds_mean', 'rsds_median', 'rsds_min',
       'rsds_max', 'rsds_std', 'pr_sum', 'mass_balance'],
      dtype='object')

In [5]:
fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/seasonal/r06/loygo.csv'
pd.read_csv(fn).columns

Index(['year', 'rgi_id', 'GLIMSId', 'CenLat', 'CenLon', 'Slope', 'Aspect',
       'Area', 'mass_balance', 'Zmed', 'Zmin', 'Zmax', 'pr_abl_sum',
       'pr_acc_sum', 'tas_abl_mean', 'tas_acc_mean', 'rsds_abl_mean',
       'rsds_acc_mean'],
      dtype='object')

In [6]:
fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/monthly/r06/loygo.csv'
pd.read_csv(fn).columns

Index(['rgi_id', 'year', 'GLIMSId', 'CenLon', 'CenLat', 'Slope', 'Area',
       'Aspect', 'Zmed', 'Zmin',
       ...
       'pr_monthly_total_04', 'pr_monthly_total_05', 'pr_monthly_total_06',
       'pr_monthly_total_07', 'pr_monthly_total_08', 'pr_monthly_total_09',
       'pr_monthly_total_10', 'pr_monthly_total_11', 'pr_monthly_total_12',
       'mass_balance'],
      dtype='object', length=144)

In [7]:
for col in pd.read_csv(fn).columns:
    if '01' in col:
        print(col)

tas_mean_01
tas_median_01
tas_min_01
tas_max_01
tas_std_01
rsds_mean_01
rsds_median_01
rsds_min_01
rsds_max_01
rsds_std_01
pr_monthly_total_01

# For deletion

In [17]:
inp_dir='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/seasonal/'
reg_subdir='r06'
inp_fld=os.path.join(inp_dir,reg_subdir) #inp_dir+reg_subdir

train_fn=inp_fld+'/train.csv'
logo_fn=inp_fld+'/logo.csv'
loyo_fn=inp_fld+'/loyo.csv'
logyo_fn=inp_fld+'/loygo.csv'
for_preds_fn=inp_fld+'/for_preds.csv'
full_fn=inp_fld+'/full.csv'

# Read data
train_df=pd.read_csv(train_fn)
logo_df=pd.read_csv(logo_fn)
loyo_df=pd.read_csv(loyo_fn)
logyo_df=pd.read_csv(logyo_fn)
for_preds_df=pd.read_csv(for_preds_fn)
full_df = pd.read_csv(full_fn)

In [18]:
# Convert the column Year in date time format if not already in pandas datetime format
if type(train_df['year'][0]) == np.int64:
    train_df['year'] = pd.to_datetime(train_df['year'], format='%Y')
else:
    train_df['year'] = pd.to_datetime(train_df['year'], format="%Y-%m-%d")
if type(logo_df['year'][0]) == np.int64:
    logo_df['year'] = pd.to_datetime(logo_df['year'], format='%Y')
else:
    logo_df['year'] = pd.to_datetime(logo_df['year'], format="%Y-%m-%d")
if type(loyo_df['year'][0]) == np.int64:
    loyo_df['year'] = pd.to_datetime(loyo_df['year'], format='%Y')
else:
    loyo_df['year'] = pd.to_datetime(loyo_df['year'], format="%Y-%m-%d")
if type(logyo_df['year'][0]) == np.int64:
    logyo_df['year'] = pd.to_datetime(logyo_df['year'], format='%Y')
else:
    logyo_df['year'] = pd.to_datetime(logyo_df['year'], format="%Y-%m-%d")
if type(for_preds_df['year'][0]) == np.int64:
    for_preds_df['year'] = pd.to_datetime(for_preds_df['year'], format='%Y')
else:
    for_preds_df['year'] = pd.to_datetime(for_preds_df['year'], format="%Y-%m-%d")
if type(full_df['year'][0]) == np.int64:
    full_df['year'] = pd.to_datetime(full_df['year'], format='%Y')
else:
    full_df['year'] = pd.to_datetime(full_df['year'], format="%Y-%m-%d")

In [10]:
type(full_df['year'][0])

str

In [19]:
full_df['year'][0]

Timestamp('1979-01-01 00:00:00')

In [1]:
import pandas as pd

In [12]:
r19_fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/seasonal/r19/full.csv'
r06_fn='/scratch/b5at/ranil.b5at/data_prep_tools/data_for_model/w5e5runs/seasonal/r05/full.csv'
r06_df=pd.read_csv(r06_fn)
r19_df=pd.read_csv(r19_fn)
r06_df.head(2)

,year,rgi_id,GLIMSId,CenLat,CenLon,Slope,Aspect,Area,mass_balance,Zmed,Zmin,Zmax,pr_abl_sum,pr_acc_sum,tas_abl_mean,tas_acc_mean,rsds_abl_mean,rsds_acc_mean
0,1979-01-01,RGI60-05.00001,G306709E66077N,66.0765,-53.2909,29.0,25,0.168,1818.565814,868,689,995,199.520012,213.159992,276.129996,264.421436,189.869734,48.822563
1,1980-01-01,RGI60-05.00001,G306709E66077N,66.0765,-53.2909,29.0,25,0.168,998.103783,868,689,995,102.770005,153.970000,276.810006,265.578564,193.472611,51.198818

In [14]:
r19_df.isnull().sum()

year             0
rgi_id           0
GLIMSId          0
CenLat           0
CenLon           0
Slope            0
Aspect           0
Area             0
mass_balance     0
Zmed             0
Zmin             0
Zmax             0
pr_abl_sum       0
pr_acc_sum       0
tas_abl_mean     0
tas_acc_mean     0
rsds_abl_mean    0
rsds_acc_mean    0
dtype: int64

In [7]:
train_df['mass_balance'].describe()

count    94546.000000
mean       -93.431671
std        835.009927
min      -7367.826784
25%       -515.453979
50%        -42.671342
75%        418.258916
max       3597.369212
Name: mass_balance, dtype: float64

In [8]:
train_df

,year,rgi_id,GLIMSId,CenLat,CenLon,Slope,Aspect,Area,mass_balance,Zmed,Zmin,Zmax,pr_abl_sum,pr_acc_sum,tas_abl_mean,tas_acc_mean,rsds_abl_mean,rsds_acc_mean
0,1979-01-01,RGI60-19.00001,G292519E66856S,-66.8560,-67.481,7.8,209,64.608,980.564676,-999,10,1350,1574.766290,1769.447440,269.890903,263.981238,195.243185,18.838418
1,1980-01-01,RGI60-19.00001,G292519E66856S,-66.8560,-67.481,7.8,209,64.608,-580.854380,-999,10,1350,1054.015560,810.317850,269.429848,261.358900,204.550329,23.065948
2,1981-01-01,RGI60-19.00001,G292519E66856S,-66.8560,-67.481,7.8,209,64.608,520.187170,-999,10,1350,1346.015450,1188.757934,269.542293,263.415495,194.626595,20.321455
3,1982-01-01,RGI60-19.00001,G292519E66856S,-66.8560,-67.481,7.8,209,64.608,431.799513,-999,10,1350,1215.688950,1668.646260,269.547397,264.750067,197.257860,17.677719
4,1983-01-01,RGI60-19.00001,G292519E66856S,-66.8560,-67.481,7.8,209,64.608,717.318302,-999,10,1350,1303.248400,1801.038440,269.676945,266.547552,182.044095,19.202752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94541,2015-01-01,RGI60-19.02752,G037714E46897S,-46.8972,37.714,9.6,35,0.528,-192.716717,-999,970,1170,509.160629,605.814489,279.554320,278.295952,198.118678,63.547294
94542,2016-01-01,RGI60-19.02752,G037714E46897S,-46.8972,37.714,9.6,35,0.528,375.754296,-999,970,1170,597.450106,661.759539,279.254665,278.431262,203.279785,71.524883
94543,2017-01-01,RGI60-19.02752,G037714E46897S,-46.8972,37.714,9.6,35,0.528,-52.741855,-999,970,1170,489.291905,593.262020,279.461613,278.268902,196.501450,71.534346
94544,2018-01-01,RGI60-19.02752,G037714E46897S,-46.8972,37.714,9.6,35,0.528,-965.607457,-999,970,1170,607.628955,635.712510,279.953442,278.559052,192.005370,68.499838
94545,2019-01-01,RGI60-19.02752,G037714E46897S,-46.8972,37.714,9.6,35,0.528,-322.159381,-999,970,1170,604.117324,707.617685,279.733285,278.421972,200.271163,66.544792